/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppName: typeof import('./components/AppName.vue')['default']
    CharBlock: typeof import('./components/CharBlock.vue')['default']
    CheatSheet: typeof import('./components/CheatSheet.vue')['default']
    Confetti: typeof import('./components/Confetti.vue')['default']
    Countdown: typeof import('./components/Countdown.vue')['default']
    Dashboard: typeof import('./components/Dashboard.vue')['default']
    DashboardItem: typeof import('./components/DashboardItem.vue')['default']
    FailedPage: typeof import('./components/FailedPage.vue')['default']
    Hint: typeof import('./components/Hint.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    ModalsLayer: typeof import('./components/ModalsLayer.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NoQuizToday: typeof import('./components/NoQuizToday.vue')['default']
    Play: typeof import('./components/Play.vue')['default']
    ResultFooter: typeof import('./components/ResultFooter.vue')['default']
    Settings: typeof import('./components/Settings.vue')['default']
    ShareButton: typeof import('./components/ShareButton.vue')['default']
    ShareDialog: typeof import('./components/ShareDialog.vue')['default']
    ShareImage: typeof import('./components/ShareImage.vue')['default']
    ShareText: typeof import('./components/ShareText.vue')['default']
    ToggleMask: typeof import('./components/ToggleMask.vue')['default']
    ToneSymbol: typeof import('./components/ToneSymbol.vue')['default']
    VariantLinks: typeof import('./components/VariantLinks.vue')['default']
    VDots: typeof import('./components/VDots.vue')['default']
    WelcomePage: typeof import('./components/WelcomePage.vue')['default']
    WordBlocks: typeof import('./components/WordBlocks.vue')['default']
  }
}
